/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author AJF
 */
public class objeto extends javax.swing.JPanel {

    /**
     * Creates new form objeto
     */
    String nombre="";
    String imagen="";
    boolean quitar=false;
    public boolean eliminar()
    {
        return quitar;
    }
            
    public String getNombre()
    {
        return this.nombre;
    }
    public String getImgen()
    {
        return this.imagen;
    }
    public objeto(String nombre,String nombreIMG) {
        initComponents();
        this.nombre=nombre;
        this.imagen=nombreIMG;
        this.nombreObjeto.setText(nombre);
        //this.labelImagen=imagen;
        //JLabel labelTemporal=new JLabel();
        labelImagen.setSize(50, 50);
        String path="../imagenes/"+nombreIMG+".png";
        ImageIcon imgIcon = new ImageIcon(getClass().getResource(path));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(50,50, Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        this.labelImagen.setIcon(iconoEscalado);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelImagen = new javax.swing.JLabel();
        checkEliminar = new javax.swing.JCheckBox();
        nombreObjeto = new javax.swing.JTextField();

        checkEliminar.setText("Eliminar");
        checkEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(nombreObjeto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombreObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkEliminarMouseClicked
        // TODO add your handling code here:
        if(this.checkEliminar.isSelected())
        {
            quitar=true;
        }
        else
        {
            quitar=false;
        }
    }//GEN-LAST:event_checkEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkEliminar;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JTextField nombreObjeto;
    // End of variables declaration//GEN-END:variables
}
